# Generated by Django 6.0.1 on 2026-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_viewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
