# Generated by Django 6.0.1 on 2026-01-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_viewing_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
