# Generated by Django 6.0.1 on 2026-01-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popcorn_box.movie')),
            ],
            options={
                'unique_together': {('movie', 'language')},
            },
        ),
    ]
