# Generated by Django 6.0.1 on 2026-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_movietranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='original_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
