# Generated by Django 6.0.1 on 2026-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_title_movie_original_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietranslation',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
