# Generated by Django 6.0.1 on 2026-01-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_movietranslation_is_fallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('http_method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(null=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
