# Generated by Django 6.0.1 on 2026-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_movie_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
