# Generated by Django 6.0.2 on 2026-02-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_movie_poster_path_movie_poster_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
